// The core domain entities for FlightMock
// These interfaces represent contracts — the shape every part
// of the app agrees on when talking about flights

export interface Airport {
  code: string; // IATA code e.g. "LHR", "JFK"
  name: string;
  city: string;
  country: string;
}

export interface Airline {
  code: string; // e.g. "BA", "AA"
  name: string; // e.g. "British Airways"
}

export interface Flight {
  id: string;
  origin: Airport;
  destination: Airport;
  airline: Airline;
  departureTime: Date;
  arrivalTime: Date;
  durationMinutes: number;
  price: number;
  currency: string;
  seatsAvailable: number;
}

export interface SearchQuery {
  origin: string; // Airport IATA code e.g. "LHR"
  destination: string; // Airport IATA code e.g. "JFK"
  departureDate: Date;
  returnDate?: Date; // The ? makes this optional
  passengers: number;
  cabinClass: CabinClass;
}

export type CabinClass = 'economy' | 'premium_economy' | 'business' | 'first';

export interface SearchResult {
  query: SearchQuery;
  flights: Flight[];
  searchedAt: Date;
  totalResults: number;
}

export type FlightSummary = Pick<
  Flight,
  'id' | 'airline' | 'price' | 'durationMinutes' | 'seatsAvailable'
>;
export type NewFlight = Omit<Flight, 'id'>; // For creating new flights where ID is generated by the system
export type FlightUpdate = Partial<NewFlight>; // For updates where all fields are optional
